# Generated by Django 5.1.7 on 2025-04-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
