# Generated by Django 5.1.7 on 2025-03-27 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workouts', models.ManyToManyField(to='api_test.workout')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.phase')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.player')),
            ],
        ),
    ]
