# Generated by Django 5.1.7 on 2025-03-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='set_number',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='weight',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='weights',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='rpe',
            field=models.JSONField(),
        ),
    ]
