# Generated by Django 5.1.7 on 2025-03-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_remove_workoutlog_set_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='weights',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='set_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='weight',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='rpe',
            field=models.FloatField(),
        ),
    ]
