# Generated by Django 5.1.7 on 2025-04-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_workout_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPhaseWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('week', models.IntegerField()),
                ('day', models.IntegerField()),
                ('order', models.IntegerField(default=1)),
                ('rpe', models.JSONField(default=list)),
                ('player_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_phase_workouts', to='api_test.playerphase')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.workout')),
            ],
        ),
    ]
