# Generated by Django 5.1.7 on 2025-04-04 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_playerphaseworkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveWarmup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('youtube_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerCNSWarmup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='active_warmup',
            field=models.ManyToManyField(blank=True, related_name='players', to='api_test.activewarmup'),
        ),
        migrations.CreateModel(
            name='PowerCNSExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('warmup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api_test.powercnswarmup')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='power_cns_warmups',
            field=models.ManyToManyField(blank=True, related_name='players', to='api_test.powercnswarmup'),
        ),
    ]
