# Generated by Django 5.1.7 on 2025-03-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_remove_workoutlog_weights_workoutlog_set_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='sets',
        ),
    ]
