# Generated by Django 5.1.7 on 2025-04-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0004_activewarmup_powercnswarmup_player_active_warmup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerphaseworkout',
            name='player_rpe',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
