# Generated by Django 5.1.7 on 2025-03-27 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0004_remove_workout_reps_remove_workout_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='workouts',
        ),
        migrations.CreateModel(
            name='PhaseWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_workouts', to='api_test.phase')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.workout')),
            ],
        ),
    ]
