# Generated by Django 5.1.7 on 2025-04-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0005_playerphaseworkout_player_rpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='powercnswarmup',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
