# Generated by Django 5.1.7 on 2025-03-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0005_remove_phase_workouts_phaseworkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='rpe',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='set_number',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='weight',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='sets',
            field=models.JSONField(default=()),
            preserve_default=False,
        ),
    ]
