# Generated by Django 5.1.7 on 2025-03-28 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0006_remove_workoutlog_rpe_remove_workoutlog_set_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutlog',
            old_name='sets',
            new_name='exercises',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='workout',
        ),
    ]
