# Generated by Django 5.1.7 on 2025-04-07 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0006_powercnswarmup_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThrowingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThrowingRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerThrowingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='throwing_programs', to='api_test.player')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.throwingprogram')),
            ],
        ),
        migrations.CreateModel(
            name='ThrowingProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('warmup', models.TextField(blank=True, null=True)),
                ('throwing', models.TextField(blank=True, null=True)),
                ('velo_command', models.TextField(blank=True, null=True)),
                ('arm_care', models.TextField(blank=True, null=True)),
                ('lifting', models.TextField(blank=True, null=True)),
                ('conditioning', models.TextField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api_test.throwingprogram')),
                ('plyos', models.ManyToManyField(blank=True, related_name='program_days', to='api_test.throwingroutine')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerThrowingProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('warmup', models.TextField(blank=True, null=True)),
                ('throwing', models.TextField(blank=True, null=True)),
                ('velo_command', models.TextField(blank=True, null=True)),
                ('arm_care', models.TextField(blank=True, null=True)),
                ('lifting', models.TextField(blank=True, null=True)),
                ('conditioning', models.TextField(blank=True, null=True)),
                ('player_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api_test.playerthrowingprogram')),
                ('plyos', models.ManyToManyField(blank=True, related_name='player_program_days', to='api_test.throwingroutine')),
            ],
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sets_reps', models.CharField(max_length=50)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('rpe', models.CharField(blank=True, max_length=50, null=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drills', to='api_test.throwingroutine')),
            ],
        ),
    ]
