# Generated by Django 5.1.7 on 2025-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0007_throwingprogram_throwingroutine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='throwingroutine',
            name='video_link',
        ),
        migrations.AddField(
            model_name='drill',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
