# Generated by Django 5.1.7 on 2025-03-30 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0007_rename_sets_workoutlog_exercises_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCorrectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_players', to='api_test.corrective')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_correctives', to='api_test.player')),
            ],
        ),
    ]
