# Generated by Django 5.1.7 on 2025-04-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0008_remove_throwingroutine_video_link_drill_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='throwingprogram',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='throwingprogram',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='throwingprogram',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='throwingprogram',
            name='start_date',
        ),
    ]
