# Generated by Django 5.1.7 on 2025-03-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0008_corrective_playercorrectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='correctives',
            field=models.ManyToManyField(blank=True, related_name='players', to='api_test.corrective'),
        ),
    ]
