# Generated by Django 5.1.7 on 2025-03-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0009_player_correctives'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerCorrectives',
        ),
    ]
