# Generated by Django 5.1.7 on 2025-04-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0009_remove_throwingprogram_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='throwingprogramday',
            name='plyos',
        ),
        migrations.AddField(
            model_name='throwingprogramday',
            name='plyos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
