# Generated by Django 5.1.7 on 2025-03-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0010_delete_playercorrectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaseworkout',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phaseworkout',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
