# Generated by Django 5.1.7 on 2025-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0010_remove_throwingprogramday_plyos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerthrowingprogramday',
            name='plyos',
        ),
        migrations.AddField(
            model_name='playerthrowingprogramday',
            name='plyos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
