# Generated by Django 5.1.7 on 2025-04-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0011_phaseworkout_day_phaseworkout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaseworkout',
            name='week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
