# Generated by Django 5.1.7 on 2025-04-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0011_remove_playerthrowingprogramday_plyos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='distance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drill',
            name='throws',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
