# Generated by Django 5.1.7 on 2025-04-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0012_drill_distance_drill_throws'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drill',
            name='sets_reps',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
