# Generated by Django 5.1.7 on 2025-04-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0012_phaseworkout_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaseworkout',
            name='default_rpe',
            field=models.JSONField(default=list),
        ),
    ]
