# Generated by Django 5.1.7 on 2025-04-11 16:48

from django.db import migrations, models


def populate_unique_emails(apps, schema_editor):
    Player = apps.get_model('api_test', 'Player')
    for player in Player.objects.all():
        # Generate a unique email for each player
        player.email = f"{player.first_name.lower()}_{player.id}@example.com"
        player.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0013_alter_drill_name_alter_drill_sets_reps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThrowingActiveWarmup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('youtube_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='player', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='throwing_active_warmups',
            field=models.ManyToManyField(blank=True, related_name='players', to='api_test.throwingactivewarmup'),
        ),
        migrations.RunPython(populate_unique_emails),  # Populate unique emails
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]