# Generated by Django 5.1.7 on 2025-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0014_throwingactivewarmup_rename_name_player_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='throwingactivewarmup',
            name='sets_reps',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
    ]
