# Generated by Django 5.1.7 on 2025-04-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0015_throwingactivewarmup_sets_reps_alter_player_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerthrowingprogramday',
            name='week_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='throwingprogramday',
            name='week_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
