# Generated by Django 5.1.7 on 2025-04-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0016_playerthrowingprogramday_week_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerthrowingprogramday',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='throwingprogramday',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
