# Generated by Django 5.1.7 on 2025-04-11 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0017_alter_playerthrowingprogramday_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmCareRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArmCareExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(blank=True, max_length=255, null=True)),
                ('exercise', models.CharField(max_length=255)),
                ('sets_reps', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api_test.armcareroutine')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='arm_care_routines',
            field=models.ManyToManyField(blank=True, related_name='players', to='api_test.armcareroutine'),
        ),
        migrations.CreateModel(
            name='PlayerArmCareRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_arm_care_routines', to='api_test.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerArmCareExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(blank=True, max_length=255, null=True)),
                ('exercise', models.CharField(max_length=255)),
                ('sets_reps', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api_test.playerarmcareroutine')),
            ],
        ),
    ]
