# Generated by Django 5.1.7 on 2025-04-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0018_armcareroutine_armcareexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armcareexercise',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerarmcareexercise',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
