# Generated by Django 5.1.7 on 2025-04-12 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0019_armcareexercise_day_playerarmcareexercise_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerarmcareroutine',
            name='name',
        ),
        migrations.AddField(
            model_name='playerarmcareroutine',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerarmcareroutine',
            name='routine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_test.armcareroutine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerarmcareroutine',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerarmcareroutine',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_arm_care_routines', to='api_test.player'),
        ),
    ]
