# Generated by Django 5.1.7 on 2025-04-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0021_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
