# Generated by Django 5.1.7 on 2025-04-15 01:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0022_alter_player_age_alter_player_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armcareexercise',
            name='day',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='phaseworkout',
            name='default_rpe',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='phaseworkout',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phaseworkout',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.phase'),
        ),
        migrations.AlterField(
            model_name='phaseworkout',
            name='reps',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='phaseworkout',
            name='sets',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
