# Generated by Django 5.1.7 on 2025-04-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0024_dailyintake'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
